server {
    server_name neurovlm.ucsd.edu;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location /llm/ {
        proxy_pass http://127.0.0.1:8002;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static/ {
        alias /home/rphammonds/neurovlm/static/;
        try_files $uri $uri/ =404;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /graphs/ {
        alias /home/rphammonds/neurovlm/graphs/;
        try_files $uri $uri/ =404;
    }

    location /study/ {
        proxy_pass http://127.0.0.1:8003/;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Prefix /study;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /study/static/ {
        alias /home/rphammonds/neurovlm/study/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/neurovlm.ucsd.edu/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/neurovlm.ucsd.edu/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = neurovlm.ucsd.edu) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name neurovlm.ucsd.edu;
    return 404;
}
